### ISSUE TITLE
[Discussion] Useful Commands?

### ISSUE THREAD

**Issue by johannesschobel** [apiato/core#50]
Inspired by https://github.com/apiato/core/issues/45, this is some sort of "What do you think" list of possible useful commands?

As there is already a `apiato:actions` command, that list all available actions, why not do something like this:
- [x] rename the signature to `apiato:list:actions`
- [x] create a `apiato:list:tasks` command that list all tasks
- [x] create a `apiato:list:dependencies` command from #45 

Any additional ideas?

**Comment by FWidm** [comment]
I'm not too sure about naming conventions in combination with `artisan` commands, would it be better to separate the available apiato commands in sub "categories" instead of crowding the `apiato:*` "namespace"?

Additionally it would be nice if we'd have a pre-determined place for the new `Commands` and additional data such as `Transformers`. 

Currently nothing comes to my mind in terms of new commands though :).

**Comment by johannesschobel** [comment]
Hey @FWidm , thanks for your input. I have no problem with the additional `apiato:*` "namespace", as these commands do belong to apiato. So why not? 😀 

The other question is answered in #45
