### ISSUE TITLE
Dto with required fields says : Object is missing required value

### ISSUE THREAD

**Issue by chenavazer** [apiato/core#97]
https://github.com/apiato/core/blob/ec6f445de583273f388f7ba7e3e1fc8265f603e7/Traits/CallableTrait.php#L249

**Comment by chenavazer** [comment]
I suggests:

$transporter = new $transporterClass($request);

instead :
            $transporter = new $transporterClass;
            // "copy" everything from the request to the transporter
            $transporter->hydrate($request->all());

**Comment by johannesschobel** [comment]
Hey there, thank you very much..
I will look into this issue.. The additional `Request` parameter was added later by myself - after the `hydrate` thing was introduced.. So it might be ok to switch to using
`new $transporterClass($request);`
instead.. 

Need to look into thits..

**Comment by johannesschobel** [comment]
Hey @chenavazer ,

Just took a quick glimpse at the respective function.. Actually - i would highly prefer to do **nothing** at all in this specific case, because:
1) The method is only used, if you throw a `Request` into the `Apiato::call()` method, but define a `Transporter` in the `run(...)` method.. This is basically some rare scenarios, where the actual code is executed at all.. This is purely because of backward-compatibility, when we introduced the `DTO` stuff.. 
2) Because of 1), this method will be only temporarily in the framework, i guess.. and will be deleted in future use, i think.. 

----------------------------

Regarding your specific issue with `Object is missing required value`.. 
1) How do you pass the `Request` to the `Action` (i assume this happens when you call the action from the controller?)
2) How does your `DTO` look like? Which kind of information is flagged as `required` in your DTOs?

Can you provide some more details regarding the actual problem and / or how to reproduce this issue?!
